= Wakanda

*Challenge*

To program a command line based role playing game, with the following stories

- As a player I want to create a character
- As a player I want to explore
- As a player I want to gain experience through fighting
- As a player I want to save and resume a game

These will be the technical constraints:

- Use Java
- Libraries and Frameworks are only allowed for testing and build pipelines
-  Use best in industry agile engineering practices
- Please build for the command line

*Solution*

Libraries and Frameworks used

- Test: JUnit
- Build: maven (please download it if you don't have https://maven.apache.org/)

Usage

- To compile type: mvn package (in the same folder where the pom.xml is)
- To run type: java -jar target/Wakanda.jar (You must have write permission into the folder you are running Wakanda)

Patterns used

- MVC: To structure the solution
- Command: To run all user actions during game play.

Considerations

I always do the most elegant design that I am capable of, because of this mindset, I usually don't use comments.
All my methods are short and readable and I create lots of them =]
Unless asked for, I prefer to choose maintainability and readability over performance.
I think that this code is quite extensible, for example:

- To add new Commands or User Action you just need to create a new Command.
- To improve the setup process or add a new Feature, you just need to add a new Controller.

This code took me around 10 hours to develop and some refactoring, thanks to me I have good tests to salve users from errs :]
All asked Stories had become acceptance criteria.

Enjoy!
Cristiano Passos