flyway:
  enabled: true

spring:
  h2.console.enabled: true
  cache.type: redis
  redis:
    host: localhost
    port: 6379

oauth.clients:
  - client_id: client
    client_secret: client-secret
    scope: read,write,trust
    authorized_grant_types: password,refresh_token
    authorities: role_client,role_trusted_client
    access_token_validity: 900
    refresh_token_validity: 2592000

  - client_id: client-two
    client_secret: client-two-secret
    scope: read,write,trust
    authorized_grant_types: password,refresh_token
    authorities: role_client,role_trusted_client
    access_token_validity: 900
    refresh_token_validity: 2592000

logging.level.org.springframework.web: DEBUG
